import { execute } from '@/lib/engine'
import type { TraceStep, VisibilityReason, Xid } from '@/lib/engine'
import { BOOTSTRAP_XID } from '@/lib/engine'
import { detect } from '@/lib/detect'
import { requirePack } from '@/lib/packs'
import { getScenario } from '@/lib/scenarios'
import { describe } from '@/lib/schedule'
import type { Dictionary } from '@/lib/i18n/dictionaries'
import { scenarioLegend } from '@/lib/i18n/content'
import type { Locale } from '@/lib/i18n/locales'

/**
 * One run, followed all the way through, before the reader touches a control.
 *
 * There was nowhere to read a complete run and understand it: the landing story
 * is prose with no numbers, the hero figure is notation with no walkthrough, and
 * the tour teaches the interface rather than the concept. The only way to see a
 * run explained was to operate the workbench, which is the thing that assumes
 * you already understand it.
 *
 * This is generated by executing the real model at build time — the same
 * executor, pack and level the schedule page would use — so it cannot drift from
 * what the tool does, and the values in it are not transcribed by hand. It is a
 * server component: no interactivity, nothing shipped to the browser.
 */

const PACK_ID = 'postgres-16'
const LEVEL = 'REPEATABLE READ'
/** The same schedule one level up. The disagreement is the lesson — PRD §2. */
const CONTRAST_LEVEL = 'SERIALIZABLE'
const SCENARIO_ID = 'write-skew'

/** The single fact that decided a read, picked out of the recorded walk. */
function decisive(step: TraceStep): { reason: VisibilityReason; xid: Xid | null } | null {
  if (step.outcome.type !== 'ok' || !step.outcome.reasoning) return null
  const reasoning = step.outcome.reasoning

  // The interesting reason is the one that excluded something — a version that
  // exists and was not taken is what makes a snapshot visible as a snapshot.
  for (const key of reasoning.keys) {
    for (const version of key.considered) {
      if (!version.visible && version.because === 'creatorNotYetCommitted') {
        return { reason: version.because, xid: version.xmin }
      }
    }
  }
  for (const key of reasoning.keys) {
    const taken = key.considered.find((version) => version.visible)
    if (taken) return { reason: taken.because, xid: taken.xmin }
  }
  return null
}

export function WorkedExample({ locale, dict }: { readonly locale: Locale; readonly dict: Dictionary }) {
  const scenario = getScenario(SCENARIO_ID)
  if (!scenario) return null
  const result = execute(scenario.schedule, requirePack(PACK_ID), LEVEL)
  if (result.type !== 'trace') return null

  const contrast = execute(scenario.schedule, requirePack(PACK_ID), CONTRAST_LEVEL)
  const trace = result.trace
  const anomalies = detect(trace)
  const cause = anomalies[0]?.causeStep ?? null
  const legend = scenarioLegend(locale, scenario)

  const nameOf = (xid: Xid | null): string => {
    if (xid === null || xid === BOOTSTRAP_XID) return dict.why.initialRow
    return trace.transactions.find((txn) => txn.xid === xid)?.txn ?? `xid ${xid}`
  }

  const reasonFor = (step: TraceStep): string | null => {
    const found = decisive(step)
    if (!found) return null
    const key = (
      {
        ownWrite: 'ownWrite',
        initialRow: 'initialRow',
        creatorCommitted: 'creatorCommitted',
        creatorNotYetCommitted: 'creatorNotYetCommitted',
        levelReadsUncommitted: 'levelReadsUncommitted',
        creatorRolledBack: 'creatorRolledBack',
        supersededByVisibleWrite: 'supersededByVisibleWrite',
        newerVersionTaken: 'newerVersionTaken',
      } as const
    )[found.reason]
    return dict.why[key].replace('{txn}', nameOf(found.xid))
  }

  const readValue = (step: TraceStep): string | null => {
    if (step.outcome.type !== 'ok' || !step.outcome.read) return null
    const read = step.outcome.read
    if (read.type === 'row') return read.value === null ? dict.why.noRow : String(read.value)
    return `{${read.rows.map((row) => `${row.key}=${row.value}`).join(', ')}}`
  }

  return (
    <section aria-labelledby="worked-heading" className="mt-16">
      <h2 id="worked-heading" className="font-prose text-title">
        {dict.worked.heading}
      </h2>
      <p className="mt-3 max-w-reading text-pretty leading-relaxed text-ink-muted">{dict.worked.intro}</p>

      <p className="mt-3 font-mono text-caption text-ink-muted">
        {trace.engine} {trace.engineVersion} · {trace.level}
        {trace.aliasOf ? ` (${dict.controls.aliasNote} ${trace.aliasOf})` : ''}
      </p>

      {/* What the numbers stand for, before any of them appear. */}
      {legend ? (
        <dl className="mt-4 flex flex-wrap items-baseline gap-x-5 gap-y-1.5">
          {Object.entries(legend.keys).map(([key, meaning]) => (
            <div key={key} className="flex items-baseline gap-2">
              <dt className="font-mono text-caption">
                {dict.panels.key} {key}
              </dt>
              <dd className="text-caption text-ink-muted">{meaning}</dd>
            </div>
          ))}
          {Object.entries(legend.values).map(([value, meaning]) => (
            <div key={value} className="flex items-baseline gap-2">
              <dt className="font-mono text-caption">= {value}</dt>
              <dd className="text-caption text-ink-muted">{meaning}</dd>
            </div>
          ))}
        </dl>
      ) : null}

      <ol className="mt-6 space-y-2">
        {trace.steps.map((step) => {
          const value = readValue(step)
          const reason = reasonFor(step)
          const isCause = step.index === cause
          return (
            <li
              key={step.index}
              className={`leaf px-4 py-3 ${isCause ? 'border-l-2 border-l-conductor' : ''}`}
            >
              <div className="flex flex-wrap items-baseline gap-x-3">
                <span className="font-mono text-micro text-ink-soft">{step.index}</span>
                <span className="font-mono text-caption">{step.notation}</span>
                <span className="text-caption text-ink-muted">{describe(step.op)}</span>
                {value !== null ? (
                  <span className="font-mono text-caption">→ {value}</span>
                ) : null}
              </div>
              {reason ? <p className="mt-1.5 max-w-reading text-body">{reason}</p> : null}
              {isCause ? (
                <p className="mt-1.5 max-w-reading text-body text-conductor">
                  {anomalies[0]?.mechanism}
                </p>
              ) : null}
            </li>
          )
        })}
      </ol>

      <p className="mt-4 max-w-reading text-body">
        {dict.worked.outcome}{' '}
        <span className="font-mono">
          {trace.finalState.map((row) => `${row.key}=${row.value}`).join('  ')}
        </span>
      </p>
      <p className="mt-2 max-w-reading text-body text-ink-muted">{dict.worked.close}</p>

      {/*
        The same schedule, one level up. Changing the level in the workbench
        replaces the run, so the comparison the whole project rests on could
        only ever be held in the reader's head. Here both are on the page.
      */}
      {contrast.type === 'trace' ? (
        <div className="mt-10 border-t border-staff-faint pt-8">
          <h3 className="font-prose text-section">{dict.worked.contrastHeading}</h3>
          <p className="mt-2 max-w-reading text-body text-ink-muted">{dict.worked.contrastBody}</p>
          <p className="mt-3 font-mono text-caption text-ink-muted">
            {contrast.trace.engine} {contrast.trace.engineVersion} · {contrast.trace.level}
          </p>

          <ol className="mt-4 space-y-1.5">
            {contrast.trace.steps.map((step) => {
              const failed = step.outcome.type === 'error'
              return (
                <li
                  key={step.index}
                  className={`flex flex-wrap items-baseline gap-x-3 rounded-md px-3 py-1.5 ${
                    failed ? 'bg-conductor-wash/50' : ''
                  }`}
                >
                  <span className="font-mono text-micro text-ink-soft">{step.index}</span>
                  <span className="font-mono text-caption">{step.notation}</span>
                  {step.outcome.type === 'error' ? (
                    <span className="font-mono text-caption text-conductor">
                      {step.outcome.code} {step.outcome.message}
                    </span>
                  ) : null}
                </li>
              )
            })}
          </ol>

          <p className="mt-4 max-w-reading text-body">
            {dict.worked.outcome}{' '}
            <span className="font-mono">
              {contrast.trace.finalState.map((row) => `${row.key}=${row.value}`).join('  ')}
            </span>
          </p>
          <p className="mt-2 max-w-reading text-body text-ink-muted">{dict.worked.contrastOutcome}</p>
        </div>
      ) : null}
    </section>
  )
}
